# Generated by Django 5.2.14 on 2026-07-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_watchedhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(help_text='The unique database tracking ID from TMDB.')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', help_text="Discriminator column ('movie' or 'tv').", max_length=10)),
                ('data', models.JSONField(help_text='Stores the raw TMDb API detail response JSON payload.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the cache record was synced.')),
            ],
            options={
                'verbose_name': 'Cached Media Item',
                'verbose_name_plural': 'Cached Media Items',
                'unique_together': {('media_id', 'media_type')},
            },
        ),
    ]
