# Generated by Django 5.2.14 on 2026-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cachedmedia_is_manual_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Name of the genre (e.g. Crime, Action).', max_length=100, unique=True)),
                ('data', models.JSONField(help_text='Stores the JSON list of discovered media items.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when this genre cache was synced.')),
            ],
            options={
                'verbose_name': 'Genre Cache',
                'verbose_name_plural': 'Genre Caches',
            },
        ),
    ]
