# Generated by Django 5.2.14 on 2026-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_genrecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_index=True, help_text='ID of the movie/show being viewed.')),
                ('target_id', models.IntegerField(help_text='ID of the recommended movie/show.')),
                ('score', models.FloatField(help_text='Cosine similarity score.')),
                ('media_type', models.CharField(help_text="Discriminator column ('movie' or 'tv').", max_length=10)),
            ],
            options={
                'verbose_name': 'Cached Recommendation',
                'verbose_name_plural': 'Cached Recommendations',
                'indexes': [models.Index(fields=['source_id', 'media_type'], name='core_cached_source__cb9a83_idx')],
            },
        ),
    ]
