# Generated by Django 5.2.14 on 2026-08-06 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cachedrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the watch group.', max_length=255)),
                ('invite_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique invite token.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='Owner of the group.', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(help_text='Users belonging to this group.', related_name='watch_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch Group',
                'verbose_name_plural': 'Watch Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(help_text='The TMDB identifier.')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(help_text='The user who added this title.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Associated Watch Group.', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='core.watchgroup')),
            ],
            options={
                'verbose_name': 'Shared Watchlist Item',
                'verbose_name_plural': 'Shared Watchlist Items',
                'ordering': ['-added_at'],
                'unique_together': {('group', 'media_id', 'media_type')},
            },
        ),
    ]
