# Generated by Django 5.2.14 on 2026-08-30 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_recommendationfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinueWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=50)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('episode_title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continue_watching_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Continue Watching',
                'verbose_name_plural': 'Continue Watching Logs',
                'ordering': ['-last_watched'],
                'unique_together': {('user', 'media_id', 'media_type')},
            },
        ),
    ]
