# Generated by Django 5.2.14 on 2026-08-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_continuewatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuewatching',
            name='total_episodes_in_season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
