# Generated by Django 5.2.14 on 2026-09-02 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_continuewatching_total_episodes_in_season'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(default='movie', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('seconds_watched', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exact_watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exact Watch Progress',
                'verbose_name_plural': 'Exact Watch Progress Logs',
                'unique_together': {('user', 'media_id', 'media_type')},
            },
        ),
    ]
