# Generated by Django 5.2.14 on 2026-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userwatchprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchprogress',
            name='last_position',
            field=models.IntegerField(default=0, help_text='Exact timestamp position in seconds where user paused/stopped watching.'),
        ),
    ]
