# Generated by Django 5.2.14 on 2026-09-02 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userwatchprogress_last_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mediareview',
            index=models.Index(fields=['user', 'media_id', 'media_type'], name='core_mediar_user_id_f6d4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='moviewatchlist',
            index=models.Index(fields=['user', 'media_id', 'media_type'], name='core_moview_user_id_bec749_idx'),
        ),
        migrations.AddIndex(
            model_name='userwatchprogress',
            index=models.Index(fields=['user', 'media_id', 'media_type'], name='core_userwa_user_id_ac7d9f_idx'),
        ),
    ]
