"""
Django settings for cinematch_project project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if it exists (for local development)
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                key, val = line.split('=', 1)
                os.environ[key.strip()] = val.strip().strip("'").strip('"')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-cinematch-local-dev-key-change-in-prod-123456789')

DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true' if 'RENDER' in os.environ else True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname:
    ALLOWED_HOSTS.append(render_external_hostname)

# Support additional hosts configured via the Render environment panel
extra_hosts = os.environ.get('ALLOWED_HOSTS')
if extra_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in extra_hosts.split(',') if host.strip()])



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_recaptcha',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cinematch_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notifications_unread_count',
                'core.context_processors.analytics_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'cinematch_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If running on Render or if DATABASE_URL is set, use PostgreSQL
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# 🌌 Paste this configuration right here:
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Custom Authentication URL redirection rules (Unit 9)
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

# Security: Referrer Policy — allows origin header to pass to cross-origin
# embedding servers (e.g. YouTube iframe) while keeping the full URL private.
# Reference: https://docs.djangoproject.com/en/5.2/ref/settings/#secure-referrer-policy
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# External TMDB API Key (Unit 7: REST API Integration)
TMDB_API_KEY = os.environ.get('TMDB_API_KEY', '') or '41fc74ce5602882786e1e9d4933fdcc6'

WATCHMODE_API_KEY = os.environ.get('WATCHMODE_API_KEY', '')

# External OMDb API Key (Unit 7: REST API Integration)
OMDB_API_KEY = os.environ.get('OMDB_API_KEY', '')

# TasteDive API Key
TASTEDIVE_API_KEY = os.environ.get('TASTEDIVE_API_KEY', '')

# Custom CSRF and Session cookie names to prevent conflicts on localhost:8000
CSRF_COOKIE_NAME = 'cinematch_csrftoken'
SESSION_COOKIE_NAME = 'cinematch_sessionid'

# Caching Configuration: Activate Local Memory Cache (LocMemCache)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'cinematch-local-memory-cache',
    }
}

# Google reCAPTCHA Configuration (Defaults to Google's official public test keys for universal domain support)
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')

# Silence production check error when test keys or defaults are used
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

# Google Analytics 4 Measurement ID
GA_MEASUREMENT_ID = os.environ.get('GA_MEASUREMENT_ID', '')

# Google Gemini AI API Key for CineBot Assistant
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', 'AIzaSyCB4WojtXLAdCiCd07QzsOtWZutfGuVfWE')


