# Generated by Django 5.2.14 on 2026-07-03 12:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short biography of the user.', max_length=500)),
                ('favorite_genre', models.CharField(blank=True, help_text="User's preferred movie/TV genre.", max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(help_text='The unique TMDB database identifier being reviewed.')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', help_text='Distinguishes whether this review belongs to a movie or a TV show.', max_length=10)),
                ('rating', models.IntegerField(help_text='Integer rating from 1 (lowest) to 5 (highest) stars.', validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1 star.'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5 stars.')])),
                ('review_text', models.TextField(help_text="User's detailed comments regarding the movie or TV show.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the review was written.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(help_text='The unique tracking ID from the TMDB dataset.')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', help_text="Discriminator column to distinguish between 'movie' and 'tv' show records.", max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the media was saved to the watchlist.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movie Watchlist Item',
                'verbose_name_plural': 'Movie Watchlist Items',
                'unique_together': {('user', 'media_id', 'media_type')},
            },
        ),
    ]
