# Generated by Django 5.2.14 on 2026-07-08 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(help_text='Watch duration in minutes.')),
                ('rating', models.FloatField(blank=True, help_text='Rating given by user (1 to 10).', null=True)),
                ('genres', models.CharField(help_text='Comma-separated genre names.', max_length=255)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
