# Generated by Django 5.2.14 on 2026-07-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cachedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmedia',
            name='is_manual_override',
            field=models.BooleanField(default=False, help_text='Enables overriding the provider data manually with verified streaming networks.'),
        ),
        migrations.AddField(
            model_name='cachedmedia',
            name='manual_providers',
            field=models.JSONField(blank=True, default=list, help_text="Custom list of providers: [{'name': 'Netflix', 'logo_url': '...', 'web_url': '...'}]", null=True),
        ),
    ]
